# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-24 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveyApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.TextField()),
                ('question_type', models.CharField(blank=True, max_length=100, null=True)),
                ('answer_option', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='question',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyApi.Project'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyApi.Question'),
        ),
    ]
